spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    password: "gamemode1910"
    url: jdbc:mysql://localhost:3306/shelter?allowPublicKeyRetrieval=true&useSSL=false&createDatabaseIfNotExist=true
    username: "root"
  jpa:
    hibernate:
      ddl-auto: create-drop
    open-in-view: false
    properties:
      hibernate:
        format_sql: true